function testspiral(pfile)


sprec1(pfile,'m', 'n',128);
sprec1(pfile,'h','com','N','fy', 'n', 128);

clear all

pvols = dir('p_vol*.nii');
pvolname = pvols(1).name;

ortho2005([],'tseries_file', pvolname,...
    'roitype','sphere',...
    'roisize',1,...
    'wscale',[-pi pi]*1e3, ...
    'interact',1 ...
    );

clear all; 
vols = dir('vol*.nii');
volname = vols(1).name;

ortho2005([],'tseries_file', volname,...
    'roitype','sphere',...
    'roisize',1,...
    'wscale',[], ...
    'interact',1 ...
    );

return
