function info = useoriginalfieldnames(hdr)
% useoriginalfieldnames.m - quick lookup table that assigns fieldnames of
% header structure to old version naming
% 
% INPUTS
% hdr - struct, header obtained from read_gehdr.m
% 
% OUTPUTS
% info - struct, header with fields named the "old way"
% 
% EXAMPLE
% strFile = '/work/new_scanner/pfiles_from_here/P83456.7';
% fid = fopen(strFile, 'r', 'l');
% hdr = read_gehdr(fid);
% info = useoriginalfieldnames(hdr);

% Author - Krisanne Litinas
% $Id: useoriginalfieldnames.m 1279 2014-03-24 20:06:25Z klitinas $
% $HeadURL: svn+ssh://klitinas@anger.engin.umich.edu/svn/matlab/img/trunk/useoriginalfieldnames.m $

info.s1.rdbm_rev = hdr.rdb.rdbm_rev;
info.s1.run_int = hdr.rdb.run_int;
info.s1.scan_seq = hdr.rdb.scan_seq;
info.s1.run_char = hdr.rdb.run_char;
info.s1.scan_date = hdr.rdb.scan_date;
info.s1.scan_time = hdr.rdb.scan_time;
info.s1.logo = hdr.rdb.logo;
info.s1.file_contents = hdr.rdb.file_contents;
info.s1.lock_mode = hdr.rdb.lock_mode;
info.s1.dacq_ctrl = hdr.rdb.dacq_ctrl;
info.s1.recon_ctrl = hdr.rdb.recon_ctrl;
info.s1.exec_ctrl = hdr.rdb.exec_ctrl;
info.s1.scan_type = hdr.rdb.scan_type;
info.s1.data_collect_type = hdr.rdb.data_collect_type;
info.s1.data_format = hdr.rdb.data_format;
info.s1.recon = hdr.rdb.recon;
info.s1.datacq = hdr.rdb.datacq;
info.s1.npasses = hdr.rdb.npasses;
info.s1.npomp = hdr.rdb.npomp;
info.s1.nslices = hdr.rdb.nslices;
info.s1.nechoes = hdr.rdb.nechoes;
info.s1.navs = hdr.rdb.navs;
info.s1.nframes = hdr.rdb.nframes;
info.s1.baseline_views = hdr.rdb.baseline_views;
info.s1.hnover = hdr.rdb.hnover;
info.s1.frame_size = hdr.rdb.frame_size;
info.s1.point_size = hdr.rdb.point_size;
info.s1.hdr_vquant = hdr.rdb.vquant;
info.s1.cheart = hdr.rdb.cheart;
info.s1.ctr = hdr.rdb.ctr;
info.s1.ctrr = hdr.rdb.ctrr;
info.s1.initpass = hdr.rdb.initpass;
info.s1.incrpass = hdr.rdb.incrpass;
info.s1.method_ctrl = hdr.rdb.method_ctrl;
info.s1.da_xres = hdr.rdb.da_xres;
info.s1.da_yres = hdr.rdb.da_yres;
info.s1.rc_xres = hdr.rdb.rc_xres;
info.s1.rc_yres = hdr.rdb.rc_yres;
info.s1.im_size = hdr.rdb.im_size;
info.s1.rc_zres = hdr.rdb.rc_zres;
info.s1.raw_pass_size = hdr.rdb.raw_pass_size_deprecated;
info.s1.sspsave = hdr.rdb.sspsave_deprecated;
info.s1.udasave = hdr.rdb.udasave_deprecated;
info.s1.fermi_radius = hdr.rdb.fermi_radius;
info.s1.fermi_width = hdr.rdb.fermi_width;
info.s1.fermi_ecc = hdr.rdb.fermi_ecc;
info.s1.clip_min = hdr.rdb.clip_min;
info.s1.clip_max = hdr.rdb.clip_max;
info.s1.default_offset = hdr.rdb.default_offset;
info.s1.xoff = hdr.rdb.xoff;
info.s1.yoff = hdr.rdb.yoff;
info.s1.nwin = hdr.rdb.nwin;
info.s1.ntran = hdr.rdb.ntran;
info.s1.scalei = hdr.rdb.scalei;
info.s1.scaleq = hdr.rdb.scaleq;
info.s1.rotation = hdr.rdb.rotation;
info.s1.transpose = hdr.rdb.transpose;
info.s1.kissoff_views = hdr.rdb.kissoff_views;
info.s1.slblank = hdr.rdb.slblank;
info.s1.gradcoil = hdr.rdb.gradcoil;
info.s1.ddaover = hdr.rdb.ddaover;
info.s1.sarr = hdr.rdb.sarr;
info.s1.fd_tr = hdr.rdb.fd_tr;
info.s1.fd_te = hdr.rdb.fd_te;
info.s1.fd_ctrl = hdr.rdb.fd_ctrl;
info.s1.algor_num = hdr.rdb.algor_num;
info.s1.fd_df_dec = hdr.rdb.fd_df_dec;
info.s1.dab = interleave_matrices(hdr.rdb.dab_start_rcv',hdr.rdb.dab_stop_rcv');
%fread(id, 8, 'short');  % kluge for type RDB_MULTI_RCV_TYPE
% hdr.rdb.dab_start_rcv = buff(1:2:end);  % kluge for type RDB_MULTI_RCV_TYPE
% hdr.rdb.dab_stop_rcv = buff(2:2:end);  % kluge for type RDB_MULTI_RCV_
info.s1.user0 = hdr.rdb.user0;
info.s1.user1 = hdr.rdb.user1;
info.s1.user2 = hdr.rdb.user2;
info.s1.user3 = hdr.rdb.user3;
info.s1.user4 = hdr.rdb.user4;
info.s1.user5 = hdr.rdb.user5;
info.s1.user6 = hdr.rdb.user6;
info.s1.user7 = hdr.rdb.user7;
info.s1.user8 = hdr.rdb.user8;
info.s1.user9 = hdr.rdb.user9;
info.s1.user10 = hdr.rdb.user10;
info.s1.user11 = hdr.rdb.user11;
info.s1.user12 = hdr.rdb.user12;
info.s1.user13 = hdr.rdb.user13;
info.s1.user14 = hdr.rdb.user14;
info.s1.user15 = hdr.rdb.user15;
info.s1.user16 = hdr.rdb.user16;
info.s1.user17 = hdr.rdb.user17;
info.s1.user18 = hdr.rdb.user18;
info.s1.user19 = hdr.rdb.user19;
info.s1.v_type = hdr.rdb.v_type;
info.s1.v_coefxa = hdr.rdb.v_coefxa;
info.s1.v_coefxb = hdr.rdb.v_coefxb;
info.s1.v_coefxc = hdr.rdb.v_coefxc;
info.s1.v_coefxd = hdr.rdb.v_coefxd;
info.s1.v_coefya = hdr.rdb.v_coefya;
info.s1.v_coefyb = hdr.rdb.v_coefyb;
info.s1.v_coefyc = hdr.rdb.v_coefyc;
info.s1.v_coefyd = hdr.rdb.v_coefyd;
info.s1.v_coefza = hdr.rdb.v_coefza;
info.s1.v_coefzb = hdr.rdb.v_coefzb;
info.s1.v_coefzc = hdr.rdb.v_coefzc;
info.s1.v_coefzd = hdr.rdb.v_coefzd;
info.s1.vm_coef1 = hdr.rdb.vm_coef1;
info.s1.vm_coef2 = hdr.rdb.vm_coef2;
info.s1.vm_coef3 = hdr.rdb.vm_coef3;
info.s1.vm_coef4 = hdr.rdb.vm_coef4;
info.s1.v_venc = hdr.rdb.v_venc;
info.s1.spectral_width = hdr.rdb.spectral_width;
info.s1.csi_dims = hdr.rdb.csi_dims;
info.s1.xcsi = hdr.rdb.xcsi;
info.s1.ycsi = hdr.rdb.ycsi;
info.s1.zcsi = hdr.rdb.zcsi;
info.s1.roilenx = hdr.rdb.roilenx;
info.s1.roileny = hdr.rdb.roileny;
info.s1.roilenz = hdr.rdb.roilenz;
info.s1.roilocx = hdr.rdb.roilocx;
info.s1.roilocy = hdr.rdb.roilocy;
info.s1.roilocz = hdr.rdb.roilocz;
info.s1.vumdwell = hdr.rdb.numdwell;
info.s1.ps_command = hdr.rdb.ps_command;
info.s1.ps_mps_r1 = hdr.rdb.ps_mps_r1;
info.s1.ps_mps_r2 = hdr.rdb.ps_mps_r2;
info.s1.ps_mps_tg = hdr.rdb.ps_mps_tg;
info.s1.ps_mps_freq = hdr.rdb.ps_mps_freq;
info.s1.ps_aps_r1 = hdr.rdb.ps_aps_r1;
info.s1.ps_aps_r2 = hdr.rdb.ps_aps_r2;
info.s1.ps_aps_tg = hdr.rdb.ps_aps_tg;
info.s1.ps_aps_freq = hdr.rdb.ps_aps_freq;
info.s1.ps_scalei = hdr.rdb.ps_scalei;
info.s1.ps_scaleq = hdr.rdb.ps_scaleq;
info.s1.ps_snr_warning = hdr.rdb.ps_snr_warning;
info.s1.ps_aps_or_mps = hdr.rdb.ps_aps_or_mps;
info.s1.ps_mps_bitmap = hdr.rdb.ps_mps_bitmap;
info.s1.ps_powerspec = hdr.rdb.ps_powerspec;
info.s1.ps_filler1 = hdr.rdb.ps_filler1;
info.s1.ps_filler2 = hdr.rdb.ps_filler2;
info.s1.rec_noise_mean = hdr.rdb.obsolete1;
info.s1.rec_noise_std = hdr.rdb.obsolete2;
info.s1.halfecho = hdr.rdb.halfecho;
info.s1.im_size_y = hdr.rdb.im_size_y;
info.s1.data_collect_type1 = hdr.rdb.data_collect_type1;
info.s1.freq_scale = hdr.rdb.freq_scale;
info.s1.phase_scale = hdr.rdb.phase_scale;
info.s1.ovl = hdr.rdb.ovl;
info.s1.pclin = hdr.rdb.pclin;
info.s1.pclinnpts = hdr.rdb.pclinnpts;
info.s1.pclinorder = hdr.rdb.pclinorder;
info.s1.pclinavg = hdr.rdb.pclinavg;
info.s1.pccon = hdr.rdb.pccon;
info.s1.pcconnpts = hdr.rdb.pcconnpts;
info.s1.pcconorder = hdr.rdb.pcconorder;
info.s1.pcextcorr = hdr.rdb.pcextcorr;
info.s1.pcgraph = hdr.rdb.pcgraph;
info.s1.pcileave = hdr.rdb.pcileave;
info.s1.hdbestky = hdr.rdb.hdbestky;
info.s1.pcctrl = hdr.rdb.pcctrl;
info.s1.pcthrespts = hdr.rdb.pcthrespts;
info.s1.pcdiscbeg = hdr.rdb.pcdiscbeg;
info.s1.pcdiscmid = hdr.rdb.pcdiscmid;
info.s1.pcdiscend = hdr.rdb.pcdiscend;
info.s1.pcthrespct = hdr.rdb.pcthrespct;
info.s1.pcspacial = hdr.rdb.pcspacial;
info.s1.pctempporal = hdr.rdb.pctemporal;
info.s1.pcspare = hdr.rdb.pcspare;
info.s1.ileaves = hdr.rdb.ileaves;
info.s1.kydir = hdr.rdb.kydir;
info.s1.alt = hdr.rdb.alt;
info.s1.reps = hdr.rdb.reps;
info.s1.ref = hdr.rdb.ref;
info.s1.pcconnorm = hdr.rdb.pcconnorm;
info.s1.pcconfitwt = hdr.rdb.pcconfitwt;
info.s1.pclinnorm = hdr.rdb.pclinnorm;
info.s1.pclinfitwt = hdr.rdb.pclinfitwt;
info.s1.pcbestky = hdr.rdb.pcbestky;
info.s1.vrgf = hdr.rdb.vrgf;
info.s1.vrgfxres = hdr.rdb.vrgfxres;
info.s1.bp_corr = hdr.rdb.bp_corr;
info.s1.recv_freq_s = hdr.rdb.recv_freq_s;
info.s1.recv_freq_e = hdr.rdb.recv_freq_e;
info.s1.hniter = hdr.rdb.hniter;
info.s1.fast_rec = hdr.rdb.fast_rec;
info.s1.refframes = hdr.rdb.refframes;
info.s1.refframep = hdr.rdb.refframep;
info.s1.scnframe = hdr.rdb.scnframe;
info.s1.pasframe = hdr.rdb.pasframe;
info.s1.user_usage_tag = hdr.rdb.user_usage_tag;
info.s1.user_fill_mapMSW = hdr.rdb.user_fill_mapMSW;
info.s1.user_fill_mapLSW = hdr.rdb.user_fill_mapLSW;
info.s1.user20 = hdr.rdb.user20;
info.s1.user21 = hdr.rdb.user21;
info.s1.user22 = hdr.rdb.user22;
info.s1.user23 = hdr.rdb.user23;
info.s1.user24 = hdr.rdb.user24;
info.s1.user25 = hdr.rdb.user25;
info.s1.user26 = hdr.rdb.user26;
info.s1.user27 = hdr.rdb.user27;
info.s1.user28 = hdr.rdb.user28;
info.s1.user29 = hdr.rdb.user29;
info.s1.user30 = hdr.rdb.user30;
info.s1.user31 = hdr.rdb.user31;
info.s1.user32 = hdr.rdb.user32;
info.s1.user33 = hdr.rdb.user33;
info.s1.user34 = hdr.rdb.user34;
info.s1.user35 = hdr.rdb.user35;
info.s1.user36 = hdr.rdb.user36;
info.s1.user37 = hdr.rdb.user37;
info.s1.user38 = hdr.rdb.user38;
info.s1.user39 = hdr.rdb.user39;
info.s1.user40 = hdr.rdb.user40;
info.s1.user41 = hdr.rdb.user41;
info.s1.user42 = hdr.rdb.user42;
info.s1.user43 = hdr.rdb.user43;
info.s1.user44 = hdr.rdb.user44;
info.s1.user45 = hdr.rdb.user45;
info.s1.user46 = hdr.rdb.user46;
info.s1.user47 = hdr.rdb.user47;
info.s1.user48 = hdr.rdb.user48;
info.s1.pcfitorig = hdr.rdb.pcfitorig;
info.s1.pcshotfirst = hdr.rdb.pcshotfirst;
info.s1.pcshotlast = hdr.rdb.pcshotlast;
info.s1.pcmultegrp = hdr.rdb.pcmultegrp;
info.s1.pclinfix = hdr.rdb.pclinfix;
info.s1.pcconfix = hdr.rdb.pcconfix;
info.s1.pclinslope = hdr.rdb.pclinslope;
info.s1.pcconslope = hdr.rdb.pcconslope;
info.s1.pccoil = hdr.rdb.pccoil;
info.s1.excess = hdr.rdb.excess;
info.s8.ex_no = hdr.exam.ex_no;
info.s8.hospname = hdr.exam.hospname;
info.s8.magstrength = hdr.exam.magstrength;
info.s8.patid = hdr.exam.patidff;
info.s8.patname = hdr.exam.patnameff;
info.s8.ex_datetime = hdr.exam.ex_datetime;
info.s9.se_exno = hdr.series.se_exno;
info.s9.se_no = hdr.series.se_no;
info.s9.se_desc = hdr.series.se_desc;
info.s9.pr_sysid = hdr.series.pr_sysid;
info.s9.pansysid = hdr.series.pansysid;
info.s9.anref = hdr.series.anref;
info.s9.prtcl = hdr.series.prtcl;
info.s10.im_exno = hdr.image.im_exno;
info.s10.im_seno = hdr.image.im_seno;
info.s10.im_no = hdr.image.im_no;
info.s10.sctime = hdr.image.sctime;

% Point to rdb.user30 for slice thickness if non-zero (safer bet than the
% odd shift later in header that seems to happen sometimes)
if hdr.rdb.user30 ~= 0
    info.s10.slthick = hdr.rdb.user30;
else
    info.s10.slthick = hdr.image.slthick;
end

info.s10.tr = hdr.image.tr /1000;
info.s10.te = hdr.image.te /1000;
info.s10.fa = hdr.image.mr_flip;
info.s10.psdname = hdr.image.psdname;

% headersize hardcoded for now
info.headersize = 149788;
