function ez_fair(FAIR_Name, TI, T1art, dt,outName ,verbose)
%
% function ez_perf(FAIR_Name, TI, T1art,dt,outName [,verbose] )
%
% Computes perfusion map using Yang et al's  equation
% for FAIR experiment.  ref:  MRM 39, 825, 1998
%
% uses the files T1.dat and Mot.dat, and dt.img which are generated by 
% t1_map2.m and fair.m  Must run those before this program
% 
% TI and T1art are expressed in seconds
%
% T1 of tap water at 3T = 2.6sec.

%%  Assumed constants  %%%
lambda = 1;


h = read_hdr(sprintf('%s.hdr',FAIR_Name));

DM = read_img_data(h, sprintf('%s.img',FAIR_Name) );
Mo   = read_img_data(h,'Mot.img');

T1   = read_img_data(h,'T1.img');
T1 = T1 ./1000; % convert from ms. to seconds
R1 = 1./T1;

R1art = 1/T1art;

%dt  = read_img_data(h,'dt.img');
%dt = dt ./1000; % convert from ms. to seconds


num =  lambda .*DM .* (R1-R1art);
den =  Mo.*2.*exp(-R1art.*TI).*(1-exp(-(R1-R1art).*(TI - dt)));

f_data = (num./den) * 60 * 100; %scale to ml/min/100g

f_data(find(Mo==0))=0;

write_hdr(sprintf('%s.hdr',outName), h);
write_img_data(sprintf('%s.img',outName), f_data, h);

if nargin==6
    orthov(outName);
end
disp('Finished flow maps')

return
