function ez_perf(FAIR_Name, dim, TI, TR, outName)
%
% function ez_perf(FAIR_Name, dim, TI, TR,outName)
%
% Computes perfusion map using Kim's simple equation
% for FAIR experiment
% uses the files T1.dat and Mot.dat, which was generated by 
% t1_map.m
% 
% TI and TR are expressed in seconds


%%  Assumed constants  %%%
lambda = 0.9;

FAIR_size = dim*dim;

FAIR_data = (get_pix_arr(FAIR_Name, FAIR_size, 'int16'))';
T1_data   = (get_pix_arr('T1.dat', FAIR_size, 'int16'))';
T1_data = T1_data /1000; % convert from ms. to seconds
Mo_data   = (get_pix_arr('Mot.dat', FAIR_size, 'int16'))';

   
f_data= lambda .* FAIR_data ./(TI.*Mo_data.*(2.*exp(-TI./T1_data) -exp(-TR./T1_data))); 
f_data = f_data * 60 * 100; %scale to ml/min/100g


pFile = fopen(outName,'wb');
fwrite(pFile, f_data, 'int16');
fclose(pFile);


disp('Finished flow maps')

return
dtpad


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
