% getconstatnts --- read the mat files generated by greg and calculte the 
% mean transit times at rest and activation
% get the mean flow at rest and activation from the TR=4s data
% calculate the relative changes in them and the kappa constant 


load TTfitdata_restt
% resting raw data (transit time curve 4D data)
rest = TTimcurve;
restTT =myTTim(:);
meanrTT = mean(restTT(find(restTT)));

% look at the 4second TR data to get the resting steady state flow
rf = squeeze(TTimcurve(:,:,:,7));
rf = rf(:);
meanrf = mean(rf(find(rf)));


% ACTIVE raw data (transit time curve 4D data)
load TTfitdata_activet
act = TTimcurve;
actTT =myTTim(:);
meanaTT = mean(actTT(find(actTT(:))));

% look at the 4second TR data to get the resting steady state flow
af = squeeze(TTimcurve(:,:,:,7));
af = af(:);
meanaf = mean(af(find(af)));

%dTT = restTT - actTT;
%df = squeeze(act(:,:,:,7)) - squeeze(rest(:,:,:,7));
dTT = meanaTT - meanrTT;
dV = 18/meanaTT - 18/meanrTT;
df = meanaf - meanrf;

% relative changes.
rdTT = (meanaTT - meanrTT)/ meanrTT;
rdV = (1/meanaTT - 1/meanrTT)/ (1/meanrTT);
rdf = (meanaf - meanrf )/meanrf;
k = rdV/rdf;

fprintf('\n\n TTrest	TTact	Frest	Fact	rdTT	rdV	rdf	k');
fprintf('\n %2.2f	%2.2f	%2.2f	%2.2f	%2.2f	%2.2f	%2.2f	%2.2f', ...
	meanrTT, meanaTT, meanrf , meanaf, 100*rdTT, 100*rdV, 100*rdf, k);

save constants
fprintf('\n ... done\n')

