function fig()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load fig                               

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Position',[547 534 560 420], ...
	'Renderer','zbuffer', ...
	'Tag','Fig1');
b = axes('Parent',a, ...
	'CameraUpVector',[0 0 1], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Position',[0.0857143 0.135714 0.566071 0.716667], ...
	'Tag','Axes1', ...
	'View',[-37.5 30], ...
	'XColor',[0 0 0], ...
	'XGrid','on', ...
	'YColor',[0 0 0], ...
	'YGrid','on', ...
	'ZColor',[0 0 0], ...
	'ZGrid','on');
c = surface('Parent',b, ...
	'CData',mat2, ...
	'EdgeColor','flat', ...
	'EdgeLighting','flat', ...
	'FaceColor',[1 1 1], ...
	'FaceLighting','none', ...
	'Tag','Axes1Surface1', ...
	'VertexNormals',mat3, ...
	'XData',mat4, ...
	'YData',mat5, ...
	'ZData',mat6);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'Position',[-20.7288 -49.3042 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','top');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-31.3454 -35.5096 0], ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','top');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-17.637 12.4982 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[14.7698 33.8655 0], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[338.4 272 68 8.8], ...
	'Style','slider', ...
	'Tag','Slider1');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','view(slider2,slider1)', ...
	'Position',[334.4 232.8 70.4 9.6], ...
	'Style','slider', ...
	'Tag','Slider2');
