function  plotfancy(X);
%	Format plotfancy(X);
%		where X is is n by 3 matrix
%
%	allows user to look at a plot from different angles	
%	cengizhan
%	4.12.96
%
%	mod 4.18.97 : rotation and axis buttons are added
%
	figure;
	fig3 = gcf;
	
	plot3(X(:,1),X(:,2),X(:,3),'.');
	xlabel('X');
	ylabel('Y');
	zlabel('Z');
	axis('equal');
	ax1=gca;
 
 	sli_azm =uicontrol(fig3,...
		'Style','slider',...
		'Position',[0.02 0.02 0.46 0.04],...
		'Units','normalized',...
		'Min',-90,'Max',90,'Value',30,...
		'CallBack',[...
		'ui_handles2 =get(gcf,''Userdata'');'...
		'sli_azm = ui_handles2(1);'...
		'sli_elv = ui_handles2(2);'...
		'ax1=ui_handles2(3);'...		
		'set(ax1,''View'',[get(sli_azm,''Val''),get(sli_elv,''Val'')]);']);

	sli_elv =uicontrol(fig3,...
		'Style','slider',...
		'Position',[0.52 0.02 0.46 0.04],...
		'Units','normalized',...
		'Min',-90,'Max',90,'Value',30,...
		'CallBack',[...
		'ui_handles2 =get(gcf,''Userdata'');'...
		'sli_azm = ui_handles2(1);'...
		'sli_elv = ui_handles2(2);'...
		'ax1=ui_handles2(3);'...					
		'set(ax1,''View'',[get(sli_azm,''Val''),get(sli_elv,''Val'')]);']);
			
	pb_axoff =	uicontrol (fig3,...
		'style','push',...
		'Pos',[.85 .9 .13 .05],...
		'Units','normalized',...
		'String','AXIS OFF',...
		'CallBack','axis off;');

	pb_axoff =	uicontrol (fig3,...
		'style','push',...
		'Pos',[.85 .84 .13 .05],...
		'Units','normalized',...
		'String','AXIS ON',...
		'CallBack','axis on;');
			
	pb_rot =	uicontrol (fig3,...
		'style','push',...
		'Pos',[.85 .78 .13 .05],...
		'Units','normalized',...
		'String','ROTATE',...
		'CallBack','ui_handles2 =get(gcf,''Userdata''); ax1=ui_handles2(3); orbit(720,72,ax1);');
	

	set(fig3,'Userdata',[sli_azm sli_elv ax1]);	

