function errorwin()
% This is the machine-generated representation of a MATLAB object
% and its children.  Note that handle values may change when these
% objects are re-created. This may cause problems with some callbacks.
% The command syntax may be supported in the future, but is currently 
% incomplete and subject to change.
%
% To re-open this system, just type the name of the m-file at the MATLAB
% prompt. The M-file and its associtated MAT-file must be on your path.

load errorwin                          

a = figure('Units','points', ...
	'Color',[0 0 0.5], ...
	'Colormap',mat0, ...
	'MenuBar','none', ...
	'PointerShapeCData',mat1, ...
	'Position',[393 513.75 262.5 183.75], ...
	'Tag','Errorbox');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0 0 0.5], ...
	'FontSize',10, ...
	'ForegroundColor',[1 1 0], ...
	'Position',[17.25 55.5 234.75 109.5], ...
	'String','Error', ...
	'Style','text', ...
	'Tag','ErrorText');
