function hdr = make_ahdr(args,scaninfo)
% Creates Analyze header structure from slices structure array

pad1(1:28) = ' ';
pad2(1:2) = ' ';
pad4(1:20) = ' ';
pad5(1:6) = ' ';
pad6(1:120) = ' ';
descrip(1:120) = ' ';
pixsz = scaninfo.opfov*10/args.nim/args.zoomer;

hdr = struct(...
      'sizeof_hdr', 348,...
      'pad1', pad1,...
      'extents', 16384,...
      'pad2', pad2,...
      'regular','r', ...
      'pad3', ' ',...
      'dims', 3,...
      'xdim', args.nim,...
      'ydim', args.nim,...
      'zdim', scaninfo.nslices,...
      'tdim', 1,...
      'pad4', pad4,...
      'datatype', 4,...   %(short int)
      'bits', 16,...
      'pad5', pad5,...
      'xsize', pixsz,...
      'ysize', pixsz,...
      'zsize', scaninfo.slthick,...
      'glmax', 0,...  % we might need this...
      'glmin', 0,...  % we might need this...
      'descrip', descrip,...
      'pad6', pad6...
      );

return
